DROP TABLE IF EXISTS spesa;

CREATE TABLE spesa (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
	quantity INT NOT NULL,
	category INT NOT NULL,
	count INT NOT NULL,
	toTake BOOLEAN NOT NULL
);
